DROP TABLE IF EXISTS People;

CREATE TABLE `People`(
    `name` VARCHAR(40),
    `office` VARCHAR(15),
    `userid` VARCHAR(15),
    `group` CHAR(3)
);

INSERT INTO People VALUES('Adam Ehlers Nyholm Thomsen','Turing-127','adament','tap');
INSERT INTO People VALUES('Allan Grønlund Jørgensen','Turing-124','jallan','phd');
INSERT INTO People VALUES('Allan Rasmusson','Ada-020','alras','phd');
INSERT INTO People VALUES('Anders Bach Nielsen','Ada-213','abachn','phd');
INSERT INTO People VALUES('Anders Ebert','Hopper-032','ebert','tap');
INSERT INTO People VALUES('Anders Enghave Larsen','Hopper-025','enghave','tap');
INSERT INTO People VALUES('Anders Hessellund Jensen','Turing-126','ahj','phd');
INSERT INTO People VALUES('Anders Møller','Turing-224','amoeller','vip');
INSERT INTO People VALUES('Anders Torp Brodersen','Wiener-131','rip','phd');
INSERT INTO People VALUES('Anette Hviid','Ada-126','ahviid','tap');
INSERT INTO People VALUES('Anja Krag Svennesen','Ada-123','aks','tap');
INSERT INTO People VALUES('Ann Eg Mølhave','Ada-116','aem','tap');
INSERT INTO People VALUES('Arne Nis Jensen','Ada-128','ajensen','tap');
INSERT INTO People VALUES('Aviaja Borup Hansen','Hopper-128','aviaja','phd');
INSERT INTO People VALUES('Balasuthas Sundararajah','Hopper-126','suthas','tap');
INSERT INTO People VALUES('Birgit Pedersen','5511-033','birgitp','tap');
INSERT INTO People VALUES('Bjarke Hammersholt Roune','Turing-021','bjarke','phd');
INSERT INTO People VALUES('Brian Bunch Christensen','Ada-020','bbc','phd');
INSERT INTO People VALUES('Brian H. Mayoh','Ada-230','brian','vip');
INSERT INTO People VALUES('Carolin Lunemann','Turing-221','carolin','phd');
INSERT INTO People VALUES('Carsten Valdemar Munk','Hopper-228','cvm','tap');
INSERT INTO People VALUES('Christer Vindberg','Ada-121','u011271','tap');
INSERT INTO People VALUES('Christian Hofer','Turing-225','hofer','phd');
INSERT INTO People VALUES('Christian Nørgaard Storm Pedersen','090-112','cstorm','vip');
INSERT INTO People VALUES('Christian Sinding Nellemann','Hopper-134','csn','tap');
INSERT INTO People VALUES('Claudio Orlandi','Turing-223','orlandi','phd');
INSERT INTO People VALUES('Clemens Nylandsted Klokmose','Hopper-117','clemens','phd');
INSERT INTO People VALUES('Doina Bucur',NULL,'doina','phd');
INSERT INTO People VALUES('Dorthe Haagen Nielsen','Ada-127','dortheas','tap');
INSERT INTO People VALUES('Ellen Kjemtrup Lindstrøm','Ada-125','ellenl','tap');
INSERT INTO People VALUES('Else Magård','Turing-114','ema','tap');
INSERT INTO People VALUES('Erik Ernst','Turing-218','eernst','vip');
INSERT INTO People VALUES('Frank Allan Hansen','Hopper-119','fah','vip');
INSERT INTO People VALUES('Fred Mosekjær Madsen','Hopper-018','fred','tap');
INSERT INTO People VALUES('Gert Læssøe Mikkelsen','Turing-218','gert','phd');
INSERT INTO People VALUES('Gerth Stølting Brodal','Turing-118','gerth','vip');
INSERT INTO People VALUES('Goncalo Teofilo Afonso Pinhei','Hopper-219','afonso','tap');
INSERT INTO People VALUES('Gudmund Skovbjerg Frandsen','Turing-028','gudmund','vip');
INSERT INTO People VALUES('Guillaume Escamocher','Turing-027','ge','phd');
INSERT INTO People VALUES('Gunnar Kramp','Hopper-232','gkramp','tap');
INSERT INTO People VALUES('Hanne Friis Jensen','Ada-115','hfj','tap');
INSERT INTO People VALUES('Hans Henrik Brandenborg Søren','Turing-021','hansh','vip');
INSERT INTO People VALUES('Henning Gregers Jensen','Ada-129','hgj','tap');
INSERT INTO People VALUES('Henrik Blunck','Turing-125','blunck','vip');
INSERT INTO People VALUES('Henrik Bærbak Christensen','Hopper-218','hbc','vip');
INSERT INTO People VALUES('Ian Zerny','Hopper-227','zerny','tap');
INSERT INTO People VALUES('Ivan Bjerre Damgård','Turing-216','ivan','vip');
INSERT INTO People VALUES('Jacob Andersen','Ada-229','andersen','phd');
INSERT INTO People VALUES('Jacob Styrup Bang','Hopper-027','styrup','tap');
INSERT INTO People VALUES('Jakob Langdal Jensen','Hopper-121','jakobl','phd');
INSERT INTO People VALUES('Jakob Løvstad Funder','Turing-221','funder','phd');
INSERT INTO People VALUES('Jan Elgaard','Hopper-032','jel','tap');
INSERT INTO People VALUES('Janus Dam Nielsen','Turing-223','fagidiot','phd');
INSERT INTO People VALUES('Jeppe Brønsted','Hopper-217','jb','phd');
INSERT INTO People VALUES('Jeppe Lauridsen','Hopper-026','jeppe','tap');
INSERT INTO People VALUES('Jesper Buus Nielsen','Turing-217','buus','vip');
INSERT INTO People VALUES('Jesper Moeslund Eshøj','Turing-121','greforb','phd');
INSERT INTO People VALUES('Jesper Nielsen','Hopper-135','jespern','phd');
INSERT INTO People VALUES('Jesper Wolff Olsen','Hopper-225','jexper','phd');
INSERT INTO People VALUES('John Rothborg Mortensen','Hopper-023','jomo','tap');
INSERT INTO People VALUES('Johnni Winther','Turing-226','jw','phd');
INSERT INTO People VALUES('Jonathan Frumer','Hopper-022','jf','tap');
INSERT INTO People VALUES('Kai Birger Nielsen','Hopper-017','bnielsen','tap');
INSERT INTO People VALUES('Kaj Grønbæk','Hopper-124','kgronbak','vip');
INSERT INTO People VALUES('Kaja P. Christiansen','Hopper-019','kaja','tap');
INSERT INTO People VALUES('Karen Johanne Kortbek','Hopper-119','kortbek','phd');
INSERT INTO People VALUES('Kari Rye Schougaard Nørgaard','Hopper-223','kari','phd');
INSERT INTO People VALUES('Karl Klose','Turing-225','klose','phd');
INSERT INTO People VALUES('Karsten Østergaard Noe','Ada-020','kn','phd');
INSERT INTO People VALUES('Kaspar Rosengreen Nielsen','Hopper-118','kaspar','vip');
INSERT INTO People VALUES('Kasper Dalgaard Larsen','Turing-127','larsen','phd');
INSERT INTO People VALUES('Kim Birkelund','Ada-213','sekhmet','phd');
INSERT INTO People VALUES('Kirsten Boddum-Andersen','Ada-130','boddum','tap');
INSERT INTO People VALUES('Klaus Marius Hansen','Hopper-222','marius','vip');
INSERT INTO People VALUES('Klaus Ostermann','Turing-220','ko','vip');
INSERT INTO People VALUES('Konstantinos Tsakalidis','Turing-126','tsakalid','phd');
INSERT INTO People VALUES('Kristian Bisgaard Lassen','Ada-223','k.b.lassen','phd');
INSERT INTO People VALUES('Kristian Ellebæk Kjær','Hopper-219','argo','phd');
INSERT INTO People VALUES('Kristoffer Arnsfelt Hansen','Turing-024','arnsfelt','vip');
INSERT INTO People VALUES('Kurt Jensen','Ada-220','kjensen','vip');
INSERT INTO People VALUES('Lars Arge','Turing-116','large','vip');
INSERT INTO People VALUES('Lars Michael Kristensen','Ada-228','kris','vip');
INSERT INTO People VALUES('Lasse Kosetski Deleuran','Turing-126','ld','phd');
INSERT INTO People VALUES('Lisa Marie Wells','Hopper-236','wells','vip');
INSERT INTO People VALUES('Mads Darø Kristensen','Hopper-118','madsk','phd');
INSERT INTO People VALUES('Mads Ingstrup','Hopper-225','ingstrup','phd');
INSERT INTO People VALUES('Mads Keblov Kjeldsen','Ada-225','keblov','tap');
INSERT INTO People VALUES('Maibritt Bodin Bodin','Ada-124','bodin','tap');
INSERT INTO People VALUES('Maiken Hillerup Fogtmann','Hopper-133','maikenhf','phd');
INSERT INTO People VALUES('Marianne Dammand Iversen','Ada-118','dammand','tap');
INSERT INTO People VALUES('Marianne Graves Petersen','Hopper-128','mgraves','vip');
INSERT INTO People VALUES('Mark Greve','Turing-123','mgreve','phd');
INSERT INTO People VALUES('Martin Joakim Geisler','Turing-218','mg','phd');
INSERT INTO People VALUES('Martin Mogensen','Hopper-217','spider','phd');
INSERT INTO People VALUES('Martin Olsen','Turing-124','mo','phd');
INSERT INTO People VALUES('Mathias Schwarz','Turing-226','schwarz','phd');
INSERT INTO People VALUES('Maurice Julien Jansen','Turing-024','mjjansen','vip');
INSERT INTO People VALUES('Michael Achenbach','Turing-226','ma','phd');
INSERT INTO People VALUES('Michael Bang Nielsen','Ada-020','bang','vip');
INSERT INTO People VALUES('Michael Bruus Pedersen','Hopper-030','bruus','tap');
INSERT INTO People VALUES('Michael Christensen','Hopper-231','toby','tap');
INSERT INTO People VALUES('Michael Edelgaard Caspersen','Ada-224','mec','vip');
INSERT INTO People VALUES('Michael Glad','Hopper-022','glad','tap');
INSERT INTO People VALUES('Michael I. Schwartzbach','Turing-222','mis','vip');
INSERT INTO People VALUES('Michael Westergaard','Ada-221','mw','vip');
INSERT INTO People VALUES('Mikkel Baun Kjærgaard','Hopper-223','mikkelbk','phd');
INSERT INTO People VALUES('Mikkel Krøigaard','Turing-218','mk','phd');
INSERT INTO People VALUES('Miroslava Sotakova','Turing-215','mirka','phd');
INSERT INTO People VALUES('Mogens Nielsen','Ada-216','mn','vip');
INSERT INTO People VALUES('Mohammad Abam','Turing-122','abam','vip');
INSERT INTO People VALUES('Morten Bohøj','Hopper-125','bohoej','phd');
INSERT INTO People VALUES('Morten Holdflod Møller','Hopper-118','mortenhm','tap');
INSERT INTO People VALUES('Morten Kyng','Hopper-226','mkyng','vip');
INSERT INTO People VALUES('Morten Nisker','Ada-120','nisker','tap');
INSERT INTO People VALUES('Morten Revsbæk','Turing-123','mrevs','phd');
INSERT INTO People VALUES('Morten Tranberg Hansen','Ada-229','mth','phd');
INSERT INTO People VALUES('Niels Olof Bouvin','Hopper-123','bouvin','vip');
INSERT INTO People VALUES('Niels Raabjerg Mathiasen','Hopper-127','nielsm','phd');
INSERT INTO People VALUES('Nikolaj Gandrup Borchorst','Hopper-125','ngandrup','tap');
INSERT INTO People VALUES('Nikolaos Triandopoulos','Turing-213','nikos','vip');
INSERT INTO People VALUES('Oksana Orlenko','Ada-126','oksana','tap');
INSERT INTO People VALUES('Olav Wedege Bertelsen','Hopper-224','olavb','vip');
INSERT INTO People VALUES('Ole Caprani','Hopper-038','ocaprani','vip');
INSERT INTO People VALUES('Ole Lehrmann Madsen','Hopper-326','olm','vip');
INSERT INTO People VALUES('Ole Østerby','Ada-227','oleby','vip');
INSERT INTO People VALUES('Olivier Danvy','Turing-228','danvy','vip');
INSERT INTO People VALUES('Orestis Telelis','Turing-023','telelis','vip');
INSERT INTO People VALUES('Per Sjødin','090-117','persj','vip');
INSERT INTO People VALUES('Peter Bro Miltersen','Turing-026','bromille','vip');
INSERT INTO People VALUES('Peter Dueholm Justesen','090-214','juste','phd');
INSERT INTO People VALUES('Peter Hachenberger','Turing-119','phachenb','vip');
INSERT INTO People VALUES('Peter Klith Bøcher','Turing-121','bocher','vip');
INSERT INTO People VALUES('Peter Møller-Nielsen','Ada-226','pmn','vip');
INSERT INTO People VALUES('Pooya Davoodi','Turing-119','pdavoodi','phd');
INSERT INTO People VALUES('Preben Holst Mogensen','Hopper-231','preben','vip');
INSERT INTO People VALUES('Pär-Ola Zander','Hopper-127','poz','vip');
INSERT INTO People VALUES('Rasmus Gude','Hopper-128','gude','tap');
INSERT INTO People VALUES('Rasmus Vinge','Hopper-030','rvinge','tap');
INSERT INTO People VALUES('Rocio Santillan','Turing-027','rocio','phd');
INSERT INTO People VALUES('Rune Bolding Broberg','Hopper-024','mihtjel','tap');
INSERT INTO People VALUES('Rune Thorbek','Turing-215','thorbek','phd');
INSERT INTO People VALUES('Sami Evangelista','Ada-221','evangeli','vip');
INSERT INTO People VALUES('Simon Bo Larsen','Hopper-230','simonbl','vip');
INSERT INTO People VALUES('Simon Bæk Carstensen','Ada-126','simonbc','tap');
INSERT INTO People VALUES('Simon Holm Jensen','Turing-218','simonhj','phd');
INSERT INTO People VALUES('Simon Tjell','Ada-223','tjell','phd');
INSERT INTO People VALUES('Srinivasa Rao Satti','Turing-122','ssrao','vip');
INSERT INTO People VALUES('Surayya Urazimbetova','Ada-225','surayya','tap');
INSERT INTO People VALUES('Susanne Bødker','Hopper-122','bodker','vip');
INSERT INTO People VALUES('Søren Besenbacher','090-114','besen','phd');
INSERT INTO People VALUES('Søren Boll Overgaard','Hopper-126','boll','tap');
INSERT INTO People VALUES('Søren Christensen','Ada-218','sorenchr','vip');
INSERT INTO People VALUES('Søren Ertmann','Hopper-021','sertmann','tap');
INSERT INTO People VALUES('Søren Madsen','Ada-120','sma','tap');
INSERT INTO People VALUES('Søren Poulsen','Ada-119','poulsen','tap');
INSERT INTO People VALUES('Thomas Dueholm Hansen','Turing-025','tdh','phd');
INSERT INTO People VALUES('Thomas Greve Kristensen','090-214','geko','phd');
INSERT INTO People VALUES('Thomas Mølhave','Turing-124','thomasm','phd');
INSERT INTO People VALUES('Thomas Riisgaard Hansen','Hopper-232','thomasr','vip');
INSERT INTO People VALUES('Thomas Sangild Sørensen','Ada-020','sangild','vip');
INSERT INTO People VALUES('Tillmann Rendel','Turing-227','rendel','phd');
INSERT INTO People VALUES('Tobias Baunbæk Christensen','Hopper-228','u063638','tap');
INSERT INTO People VALUES('Tony Gjerlufsen','Hopper-232','tonz','phd');
INSERT INTO People VALUES('Torben Bach Pedersen','Turing-117','tbp','vip');
INSERT INTO People VALUES('Troels Bjerre Sørensen','Turing-025','trold','phd');
INSERT INTO People VALUES('Ubbe Welling','Ada-217','ubbe','tap');
INSERT INTO People VALUES('Uffe Henrik Engberg','Ada-214','engberg','tap');
INSERT INTO People VALUES('Weishan Zhang','Hopper-219','zhangws','vip');
