LOAD DATA INFILE 'C:/Players.csv'
INTO TABLE players
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n';

LOAD DATA INFILE 'C:/Merch.csv'
INTO TABLE merchandise
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n';

LOAD DATA INFILE 'C:/Bosses.csv'
INTO TABLE bosses
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n';
